language: node_js
sudo: required
services:
  - redis-server
node_js:
  - '8'
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS hanbaoTest default character set utf8mb4 collate utf8mb4_unicode_ci;'
script:
  - npm test
  - npm run e2e
after_script:
  - npm run coverage