language: node_js
sudo: required
node_js:
  - '8'
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS hanbaoTest;'
  - rm package-lock.json yarn.lock
script:
  - npm test
  - npm run e2e
after_script:
  - npm run coverage